- hosts: myhosts
  connection: local
  roles:
    - role: webofmars.dummy
      become: false

  tasks:
  - name: Display /tmp/testfile contents
    command: cat /tmp/testfile
    register: command_output
  - name: Print to console
    debug:
      msg: "{{command_output.stdout}}"
  - name: Print a message
    loop: "{{ range(5) }}"
    ansible.builtin.debug:
      msg: 'I execute normally'
  - name: Print a message
    loop: "{{ range(10) }}"
    ansible.builtin.debug:
      msg: 'Dummy message'
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    become: false
    ansible.builtin.file:
      path: "{{ item }}"
      state: touch
      mode: u=rw,g=r,o=r
    loop:
      - 1.yaml
      - 2.yaml
      - a.yaml
      - b.yaml
      - cde.yaml
  - name: Add a line to a file if the file, without passing regexp
    ansible.builtin.lineinfile:
      path: "{{ item.file_name }}"
      line: "{{ lookup('pipe','date +%Y-%m-%dT%H:%M:%S') }}"
      create: true
    loop:
      - { file_name: '1.yaml', other_prop: 'value' }
      - { file_name: '2.yaml', other_prop: 'value' }
      - { file_name: 'a.yaml', other_prop: 'value' }
      - { file_name: 'b.yaml', other_prop: 'value' }
      - { file_name: 'cde.yaml', other_prop: 'value' }
      - { file_name: 'xxx.yaml', other_prop: 'value' }


  

      
