- name: Test playbook
  hosts: myhosts
  connection: local
  tasks:
    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      ansible.builtin.file:
        path: foo.conf
        state: touch
        mode: u=rw,g=r,o=r
    - name: Touch the other file, add other permissions
      ansible.builtin.file:
        path: foo2.conf
        state: touch
        mode: u+rw,g-wx,o-rwx
    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      ansible.builtin.file:
        path: foo.conf
        state: touch
        mode: u=rw,g=r,o=r
    - name: Touch the other file, add other permissions
      ansible.builtin.file:
        path: foo2.conf
        state: touch
        mode: u+rw,g-wx,o-rwx
    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      ansible.builtin.file:
        path: foo.conf
        state: touch
        mode: u=rw,g=r,o=r
    - name: Touch the other file, add other permissions
      ansible.builtin.file:
        path: foo2.conf
        state: touch
        mode: u+rw,g-wx,o-rwx
    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      ansible.builtin.file:
        path: foo.conf
        state: touch
        mode: u=rw,g=r,o=r
